### ISSUE TITLE
CRF always producing 0

### ISSUE THREAD

**Issue by Omarito2412** [farizrahman4u/keras-contrib#119]
Hello,

I've tried to use the CRF layer as an output to my Bi-LSTM CRF model and it trains well and shows reasonable accuracy by using crf.accuracy instead of "accuracy", however when I do model.predict() or predict_classes or predict_proba it always outputs 0, am I doing anything wrong?
(Tried on both Tensorflow and Theano)

crf = CRF(len(classes), sparse_target=True)

batch_size = 32
model = Sequential()
model.add(Bidirectional(LSTM(64, return_sequences=True, dropout=0.5, recurrent_dropout=0.5),input_shape=(SEQ_LENGTH, 300)))
model.add(crf)

early_stopping = EarlyStopping(monitor='val_loss', patience=1)

model.compile('adam', loss=crf.loss_function, metrics=[crf.accuracy, 'accuracy'])

Edit: I've tested the CoNLL example and it works, however for some reason my model doesn't and always outputs an array of zeros (Even on training data itself), even though the viterbi accuracy is > 95%

@linxihui Can you help please?

**Comment by linxihui** [comment]
First, for dedicate debugging, it will be nice to provide your code and part of your data for replication, as I cannot see any problem from your code. 

BTW, I don't know if you should have`'accuracy'` in `metrics` as `crf.accuracy` has the same name. Especially  when `sparse_target=True. But of course it does not explain the problem here.

**Comment by Omarito2412** [comment]
Oh nevermind about the accuracy metric, I can put my code but it requires the fast text pretrained model which might be annoying for you.
If there's anything I can run locally for you I guess it would be more convenient?

**Comment by stenverbois** [comment]
I'm having the same issue with the output. Even the example using the CoNLL dataset does not run for me with Python 3. It fails when parsing the input file:
```
  File "/usr/local/lib/python3.5/dist-packages/keras_contrib/datasets/conll2000.py", line 30, in _parse_data
    data = [[row.split() for row in sample.split('\n')] for sample in string.strip().split('\n\n')]
TypeError: a bytes-like object is required, not 'str'
```
It does work when running it with Python 2. Platform is Ubuntu 16.04.

**Comment by Omarito2412** [comment]
Hey @linxihui 
I'm still stuck with this, I'd really appreciate your help.
An example is this NER model I've trained that is a Bi-LSTM layer and a CRF layer, it scores near 99% accuracy (I'm using loss=crf.loss_function and using crf accuracy)
However when I try to test the model on a subset this happens:
(X_Test is a random split from X_Train, so there is no difference between them)

```
In [16]: model.predict_proba(X_Test[0:5])
5/5 [==============================] - 0s
Out[16]: 
array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]], dtype=float32)


```
Same output on the full test data set, same output if I use model.predict() or model.predict_classes()

Do you have any idea why is it breaking?
Here's my model

```
crf = CRF(len(classes), sparse_target=True)
batch_size = 32
model = Sequential()
model.add(Bidirectional(LSTM(256, return_sequences=True, activation='relu', dropout=0.5, recurrent_dropout=0.3),input_shape=(SEQ_LENGTH, 300)))
model.add(crf)

early_stopping = EarlyStopping(monitor='val_loss', patience=3)
reduce_lr = ReduceLROnPlateau(patience=2)
model.compile('adam', loss=crf.loss_function, metrics=[crf.accuracy])
```
My Y variable is a one hot encoding of the target classes

**Comment by Omarito2412** [comment]
Solution: don't use K.set_learning_phase()

**Comment by abhiboost** [comment]
ive the same problem. how did you solve it @Omarito2412 ?

**Comment by abhiboost** [comment]
ive the same problem. how did you solve it @Omarito2412 ?

**Comment by Omarito2412** [comment]
@abhiboost I removed the K.set_learning_phase() function call and everything worked afterwards

**Comment by linxihui** [comment]
@Omarito2412  @abhiboost  `K.set_learning_phase()` should NOT be used when doing prediction. The output at the learning phase is fake and makes not sense as CRF is non-direct graph. The key part at the training phase is the loss function, i.e., negative log likelihood.

**Comment by wangxuekui** [comment]
> @abhiboost I removed the K.set_learning_phase() function call and everything worked afterwards
Excuse me, I have never used K.set_learning_phase(),but i  also have this problem, can you tell me where to remove it? thanks

**Comment by wangxuekui** [comment]
> @Omarito2412 @abhiboost `K.set_learning_phase()` should NOT be used when doing prediction. The output at the learning phase is fake and makes not sense as CRF is non-direct graph. The key part at the training phase is the loss function, i.e., negative log likelihood.



> ive the same problem. how did you solve it @Omarito2412 ?

Excuse me ,do you know where to remove K.set_learning_phase function ?
