### ISSUE TITLE
"use_boundary" argument in CRF layer

### ISSUE THREAD

**Issue by yanghanxy** [farizrahman4u/keras-contrib#184]
Hi, @linxihui 

Thanks for your working on the CRF model, 
it works well for me on a sequence labeling task. 

I've got a question regarding the "use_boundary" argument: 
`use_boundary: Boolen (default True) inidicating if trainable start-end chain energies should be added to model.`
Could you explain what is the usage of this argument? 
And why you set True as its default value? 

Thank you!

**Comment by linxihui** [comment]
The lilkelihood with boundary in CRF is $exp(- alpha x_1 - \sum_{k=1}^{n-1} x_k^T U x_{k+1} - beta x_n) $, and  If it is `use_boundary=False`, then the likelihood will not have `alpha`, `beta`.   I see many implementation includes those boundary, that's why it default to True.  Also, with more parameter, it fills better.

**Comment by yanghanxy** [comment]
Thank you for the explanation!

**Comment by Atakey** [comment]
If "use_boundary" is true, should I add start-end sign to the train data? Or it can do it automatically?
For example, the data feed to the model :["a", "apple","on", "the","desk","."], if  I add start-end sign, that should be like this,["#B#","a", "apple","on", "the","desk",".","#E#"]
Thanks a lot.

**Comment by yanghanxy** [comment]
@Atakey, hi, you don't need to add the "start-end" tokens for using "use_boundary". 
According to the [CRF code](https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/crf.py#L392), the "use_boundary" controls whether to use the left and right boundary energy. Those two boundary energy are just like two special bias concated on the begin and end of the input sequence.
