### ISSUE TITLE
TimeDistributed ResNet

### ISSUE THREAD

**Issue by voletiv** [farizrahman4u/keras-contrib#191]
I am proposing to wrap TimeDistributed around raghakot's ResNet implementation. I shall be launching a PR. Please check https://github.com/raghakot/keras-resnet/pull/51#issuecomment-346921326 for details on the PR.

Often, CNN+LSTM architectures require a TimeDistributed version of CNNs - one CNN architecture acting on several time-distributed inputs, and then fed into an LSTM. I propose making a TimeDistributed version of ResNet.

**Comment by ahundt** [comment]
sounds great, FYI I'm closing this issue and we can continue this conversation in the relevant PRs #167 and #192.
