### ISSUE TITLE
extract_image_patches

### ISSUE THREAD

**Issue by mustgoplay** [farizrahman4u/keras-contrib#29]
Just a small inconsistency - the backend for tensorflow input variable is ssizes while for theano it's strides.  Not sure if it matters if they're the same name but seems like it's easier in the long run if they are.

Also curious why cols are before rows?

Thank you for adding this function.

**Comment by mustgoplay** [comment]
Had to change the theano version  

` patches = KTH.reshape(patches, (batch, num_channels, KTH.shape(patches)[0] // num_channels, patch_size, patch_size))
`

to:

`patches = KTH.reshape(patches, (batch, num_channels, num_rows * num_cols , patch_size, patch_size))
`

To get it to work.  The 3rd dimension otherwise was off by a factor of batch_size

**Comment by Dref360** [comment]
Will be fix in https://github.com/farizrahman4u/keras-contrib/pull/86
