### ISSUE TITLE
Upsampling and Super Resolution Layers Contribution Request

### ISSUE THREAD

**Issue by ahundt** [farizrahman4u/keras-contrib#31]
This is an issue for layers/models that help with upsampling, deconvolution, super resolution, and other cases where your output layer is larger than your input layer. One specific possibility:

 - [ ] [Atrous transpose convolutions](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d_transpose) with [tf python test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/atrous_convolution_test.py)

Others can add additional options.

**Comment by titu1994** [comment]
@ahundt I've added Subpixel Convolution Upsampling layer and its related backend changes to the DenseNet FCN PR. It should work correctly from now on tensorflow, since I just call the tensorflow depth_to_space command directly.

Still need to design a test suite for this algorithm. Since its output shape depends on the input shape it receives from the layer preceding it, it will be harder to design a suitable test for it.

**Comment by ahundt** [comment]
@titu1994 is referring to #34 

The [tf python test for atrous](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/atrous_convolution_test.py) handles multiple sizes, plus pooling layers change sizes so perhaps those could be use for examples?

**Comment by titu1994** [comment]
@ahundt I actually haven't studied AtrousConvolution layers much. I know the basics of what they do, but haven't used it much so my knowledge is purely theoretical. Can you handle the examples?

**Comment by ahundt** [comment]
@titu1994 sorry I wasn't clear, I meant using the linked test as example code on which you can base your subpixel convolution upsampling layer unit test.

**Comment by titu1994** [comment]
Hmm. That's a good point. I'll have to look into it after a few days however. I have a test drawing closer, and I need to study for it.

**Comment by titu1994** [comment]
@ahundt The SubPixelConvolution layer and its respective depth_to_space backend function tests have now been added.

**Comment by ahundt** [comment]
The first upsampling layer and depth_to_space have been merged here:
https://github.com/farizrahman4u/keras-contrib/pull/34
