### ISSUE TITLE
Review guidelines

### ISSUE THREAD

**Issue by tboquet** [farizrahman4u/keras-contrib#35]
Is it a good idea to define some rules to review a PR?
For example, because we are a lot of collaborators, it could interesting to have more than one approval to merge a PR.
What do you think?

**Comment by patyork** [comment]
[https://github.com/farizrahman4u/keras-contrib/blob/master/GUIDELINES.md#addition-of-new-features](https://github.com/farizrahman4u/keras-contrib/blob/master/GUIDELINES.md#addition-of-new-features)

**Comment by tboquet** [comment]
Right, I forgot it was defined because the last PRs have been merged with only one review. "Whenever possible, multiple Maintainers should review a pull requests before it is merged." this should be a priority.
