### ISSUE TITLE
Make Keras-contrib green again

### ISSUE THREAD

**Issue by farizrahman4u** [farizrahman4u/keras-contrib#64]
Guys, we are 2 bugs away from passing all tests :

* A shape mismatch issue in PELU which shows up in both backends
* A dim-ordering related issue in Deconv3d which shows up in TF backend alone

It would be highly appreciated if any of you could volunteer for fixing one or both of these. A Red Travis badge can damage the credibility of the whole repo (not just the modules that are failing, since people don't go through the test logs.)

Thanks.

**Comment by the-moliver** [comment]
I wholeheartedly agree. I'll fix the PELU issue today.

**Comment by the-moliver** [comment]
PELU tests now passing

**Comment by farizrahman4u** [comment]
Great! Thanks.

**Comment by the-moliver** [comment]
After some investigation Deconv3d has some larger issues and needs a bit of an overhaul to better reflect keras 2 standards. I can finish it up tomorrow...

**Comment by farizrahman4u** [comment]
@the-moliver Are you working on Deconv3d? Do you need any help?

**Comment by the-moliver** [comment]
Hey got held up with some work. Will finish it up tomorrow...

**Comment by gattia** [comment]
Hey, dont know what the bigger issues were with deconv3d, but I just fixed the dim-ordering issue or at least I think I did. There was an issue with the TF backend looking at the image dimensions as well as the kernel. There was an extra manipulation occurring. 

It worked locally and passed all the tests for my pull request #67

**Comment by the-moliver** [comment]
@gattia I merged your change to make tests pass for now, but there are still issues that I'm still working to address that the current tests aren't catching. The main issue is that any combination of backend and dim-order _should_ work, but currently don't. Given that backend and dim-order are _usually_ coupled it's not a huge issue, but still should be fixed to Keras 2 standards.

**Comment by farizrahman4u** [comment]
![good_job_boys](https://cloud.githubusercontent.com/assets/11006006/24954189/ef6402d8-1f9b-11e7-9d4e-8ef4e3d77fd5.jpg)
