### ISSUE TITLE
Best way to handle function overriding?

### ISSUE THREAD

**Issue by joeyearsley** [farizrahman4u/keras-contrib#8]
I have updated the image preprocessing to allow for FCN's, so I imagine this would fit better in Keras. However, I've also updated it to accept 'BGR' image format (Does the transform at the same time it resizes) and load grayscale to I/16 mode instead of L, however this could become an arg to be passed in also. 

If this isn't accepted into the main library and is deemed to fit best here, then what would be the best way to allow it to work nicely with Keras? 

Since it would add new lines, so keeping up to date with the main library would be a problem (i.e. merging new additions into the contrib), but overriding is hard (for users who don't want to edit keras by hand) unless it is built in.

I imagine we add another arg to the keras version which stores a list of custom object names, then loads from that list instead of the builtin functions, allowing users to override keras functions with contrib ones.

So, how should we handle situations like this?
**All of the above is related to image preprocessing only.**

**Comment by ahundt** [comment]
you should point to your changes since they can't be found based on this post. There is now https://github.com/farizrahman4u/keras-contrib for submissions that won't immediately make it to keras, though of course the code will still have to be sufficiently well written, of course.
