### ISSUE TITLE
Issue in using DSSIMObjective as loss function

### ISSUE THREAD

**Issue by temperatemarine** [farizrahman4u/keras-contrib#84]
Hi,
I am want to use difference of structural similarity as the loss function. This is my code
`from keras.models import Model`
`from keras.layers import Input, Conv2D`
`from keras.optimizers import Adam`
`from keras_contrib.losses import DSSIMObjective`
`input_shape = (1,33,33)`
`n1 = 64`
`n2 = 32`
`n3 = 1`
`f1 = 9`
`f2 = 1`
`f3 = 5`
`x = Input(shape = input_shape)`
`c1 = Conv2D(n1, (f1, f1), padding="same", kernel_initializer="he_normal", activation="relu")(x)`
`c2 = Conv2D(n2, (f2, f2), padding="same", kernel_initializer="he_normal", activation="relu")(c1)`
`c3 = Conv2D(n3, (f3, f3), padding="same", kernel_initializer="he_normal")(c2)`
`model = Model(inputs=x, outputs=c3)`
`adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8)`
`model.compile(loss=DSSIMObjective, metrics=['mse'], optimizer=adam)`

When I tried to run the program, I got the following error at the line model.compile(loss=DSSIMObjective, metrics=['mse'], optimizer=adam)
`File "/home/ldm/Desktop/SRCNN/SRCNN-hdf5/SSIM", line 23, in <module>`
`    model.compile(loss=DSSIMObjective, metrics=['mse'], optimizer=adam)`

`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 899, in compile`
`    sample_weight, mask)`

`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 441, in weighted`
`    ndim = K.ndim(score_array)`

`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 216, in ndim`
`    return x.ndim`

`AttributeError: DSSIMObjective instance has no attribute 'ndim'`

To be clear, I am using Keras 2 and theano 0.9 as backend. I suspect I didn't use DSSIMObjective in the right way, how should I use it? @farizrahman4u 
Thanks in advance.

**Comment by farizrahman4u** [comment]
```python
model.compile(loss=DSSIMObjective(), metrics=['mse'], optimizer=adam)
```
