### ISSUE TITLE
Issue with DSSIMObjective as loss function

### ISSUE THREAD

**Issue by temperatemarine** [farizrahman4u/keras-contrib#85]
Hi,
I am using DSSIMObjective as loss function. And my code is:
`n1 = 64`
`n2 = 32`
`n3 = 1`
`f1 = 9`
`f2 = 1`
`f3 = 5`
`model = Sequential()`
`model.add(Conv2D(n1, (f1, f1), padding='same', input_shape=input_shape, activation='relu'))`
`model.add(Conv2D(n2, (f2, f2), padding='same', activation='relu'))`
`model.add(Conv2D(n3, (f3, f3), padding='same'))`
`adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8) `
`model.compile(loss = DSSIMObjective(), metrics=['mse'], optimizer=adam)`
`model.fit(X, y, batch_size=128, epochs=n_epoch, shuffle='batch')`

I got the following error at the line of model.fit(X, y, batch_size=128, epochs=n_epoch, shuffle='batch')

`ValueError: cannot reshape array of size 139392 into shape (128,15488,3,3)
Apply node that caused the error: Reshape{4}(Images2Neibs{valid}.0, Join.0)
Toposort index: 113
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector)]
Inputs shapes: [(15488, 9), (4,)]
Inputs strides: [(36, 4), (8,)]
Inputs values: ['not shown', array([  128, 15488,     3,     3])]
Outputs clients: [[InplaceDimShuffle{0,x,1,2,3}(Reshape{4}.0)]]`
`Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile`
 `   builtins.execfile(filename, *where)`
 ` File "/home/ldm/Desktop/SRCNN/SRCNN-hdf5/train.py", line 74, in <module>`
`    model.compile(loss = DSSIMObjective(), metrics=['mse'], optimizer=adam)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/models.py", line 766, in compile`
`    **kwargs)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 899, in compile`
`    sample_weight, mask)`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/engine/training.py", line 430, in weighted`
  `  score_array = fn(y_true, y_pred)`
  `File "build/bdist.linux-x86_64/egg/keras_contrib/losses.py", line 39, in __call__`
`    patches_pred = KC.extract_image_patches(y_pred, kernel, kernel, 'valid', self.dim_ordering)`
`  File "build/bdist.linux-x86_64/egg/keras_contrib/backend/theano_backend.py", line 167, in extract_image_patches`
`    patches = KTH.reshape(patches, (batch, num_channels, KTH.shape(patches)[0] // num_channels, patch_size, patch_size))`
`  File "/home/ldm/anaconda2/envs/SRCNN/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 713, in reshape`
`    y = T.reshape(x, shape)`
`HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.`

BTW, if I use mse as loss function, the program can run properly with:
`model.compile(loss = losses.mean_squared_error, metrics=['mse'], optimizer=adam)`
Both  my training (X) and validation (y) data have a shape of (21884,1,33,33).
@farizrahman4u

**Comment by Dref360** [comment]
I'm on it

**Comment by temperatemarine** [comment]
Hi Dref360, I have read your comments under #4292 today. Then, I found this DSSIMObjective function from keras_contrib. I am happy to see you here :-)

**Comment by Dref360** [comment]
Will be fix in https://github.com/farizrahman4u/keras-contrib/pull/86
